name: recreateDockerImage
 on:
  push:
   branches:
    -"main"
 jobs:
  docker:
   runs-on: ubuntu-latest
   steps:
    -name: Set up QEMU
     uses: docker/setup-qemu-action@v2
    -name: Set up Docker Buildx "Buildx": Unknown word.
     uses: docker/setup-buildx-action@v2 "buildx": Unknown word.
    -name: Login to Docker Hub
     uses: docker/login-action@v2
     name: Set up Docker Buildx "Buildx": Unknown word.
     uses: docker/setup-buildx-action@v2 "buildx": Unknown word.
    -name: Login to Docker Hub
     uses: docker/login-action@v2
     with:
      username: sreenathemail "sreenathemail": Unknown word.
      password: ${{secrets.DOCKER_PASSWORD}} 
    -name: Build and push
     uses: docker/build-push-action@v4
     with:
      push: true
      tags: sreenathemail/nodehelloworld:version1 "sreenathemail": Unknown
      
